version: "3.6"
services:
    postgres:
        image: postgres:latest
        ports:
            - 5151:5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - dockernet
        environment:
            - POSTGRES_PASSWORD=A020197kc
            - POSTGRES_USER=postgres
            - POSTGRES_DB=sequelize
    redis:
        image: redis:latest
        ports:
            - 6161:6379
        networks:
            - dockernet
        depends_on:
            - postgres
    nodejs:
        image: atiakhairunican/teras-rindang-backend:main
        ports:
            - 9001-9002:9000
        env_file:
            - ./.env
        networks:
            - dockernet
        depends_on:
            - postgres
        mem_limit: 200M
        cpus: "0.5"
        deploy:
            mode: replicated
            replicas: 2
networks:
    dockernet: